package com.gs.CareerBooster.dao;

import com.gs.CareerBooster.exception.DataBaseConnectionException;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Component;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;

@Component
public class DataBaseConnection {
    @Value("${spring.datasource.url}")
    private String url;
    @Value("${spring.datasource.username}")
    private String username;
    @Value("${spring.datasource.password}")
    private String password;

    public Connection getConnection() {
        try {
            Connection conn = DriverManager.getConnection(url, username, password);
            System.out.println("Conectado com sucesso");
            return conn;
        } catch (SQLException e){
            throw new DataBaseConnectionException("Falha ao conectar ao banco de dados: " + e.getMessage(), e);
        }
    }

    public void initializeDataBase(){
        String createTableUser = """
            BEGIN
                EXECUTE IMMEDIATE '
                    CREATE TABLE users (
                        id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        password VARCHAR2(20),
                        name VARCHAR2(100),
                        email VARCHAR2(100),
                        username VARCHAR2(100),
                        area_interest VARCHAR2(50)
                    )
                ';
            EXCEPTION
                WHEN OTHERS THEN
                    IF SQLCODE != -955 THEN
                        RAISE;
                    END IF;
            END;
        """;

        String createTableCourse = """
            BEGIN
                EXECUTE IMMEDIATE '
                    CREATE TABLE courses (
                        idCourse NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        titulo VARCHAR2(100),
                        descricao VARCHAR2(100),
                        categoria VARCHAR2(100),
                        duration_hours NUMBER
                    )
                ';
            EXCEPTION
                WHEN OTHERS THEN
                    IF SQLCODE != -955 THEN
                        RAISE;
                    END IF;
            END;
        """;

        try (Connection conn = getConnection();
             Statement stmt = conn.createStatement()) {
            stmt.execute(createTableUser);
            stmt.execute(createTableCourse);
            System.out.println("Tabelas criadas/verificadas com sucesso!");
        } catch (SQLException e) {
            throw new DataBaseConnectionException("Erro ao inicializar o banco de dados: " + e.getMessage(), e);
        }
        try (Connection conn = getConnection();
             Statement stmt = conn.createStatement()){
            stmt.execute(createTableUser);
            stmt.execute(createTableCourse);
            System.out.println("Tabelas criadas/verificadas com sucesso!");
        } catch (SQLException e) {
            throw new DataBaseConnectionException("Falha ao conectar ao banco de dados: " + e.getMessage(), e);
        }


    }
}
